[profile.default]
src = "src"
out = "out"
libs = []
remappings = [
  "@openzeppelin/=node_modules/@openzeppelin/"
]
solc_version = "0.8.34"
optimizer = true
optimizer_runs = 200
via_ir = false
bytecode_hash = "ipfs"

[fmt]
line_length = 100
multiline_func_header = "all"
