#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/lib/env.sh"

require_var WORMHOLE_NETWORK
NTT_PROJECT_DIR="${NTT_PROJECT_DIR:-ntt}"

cd "$ROOT_DIR"
NTT_PROJECT_PATH="$ROOT_DIR/$NTT_PROJECT_DIR"

if [[ -f "$NTT_PROJECT_PATH/deployment.json" ]]; then
  echo "NTT project already exists at $NTT_PROJECT_PATH"
  exit 0
fi

# The repository ships with a tiny placeholder ntt/ directory so docs can live there.
# The real NTT CLI project must be generated by `ntt new` before `ntt init`.
if [[ -d "$NTT_PROJECT_PATH" ]]; then
  if find "$NTT_PROJECT_PATH" -mindepth 1 -not -name README.md -not -name overrides.example.json -print -quit | grep -q .; then
    echo "$NTT_PROJECT_PATH exists and is not an empty placeholder." >&2
    echo "Move it aside or set NTT_PROJECT_DIR to a fresh directory, then rerun." >&2
    exit 1
  fi
  rm -rf "$NTT_PROJECT_PATH"
fi

mkdir -p "$(dirname "$NTT_PROJECT_PATH")"
(
  cd "$(dirname "$NTT_PROJECT_PATH")"
  ntt new "$(basename "$NTT_PROJECT_PATH")"
)
cd "$NTT_PROJECT_PATH"
ntt init "$WORMHOLE_NETWORK"
